// this is autogenerated by running `npm run gen:i18:keys`
export type TranslationKeys =
	| "error.unknown"
	| "common.submit"
	| "common.username"
	| "common.password"
	| "common.email"
	| "auth.login"
	| "auth.logout"
	| "page.notfound"
	| "page.settings"
	| "page.home"
	| "page.users"
	| "login.title"
	| "settings.lang";
